### PR TITLE
Store cached versions of resized image

### PR DESCRIPTION
**Pull request by j-mcnally**

### CODE REVIEW

**Comment by j-mcnally** [comment]
Sorry I screwed up this request, it was embeded in my project and i was trying to copy it out and i did a bad job the first time.

**Comment by AliSoftware** [comment]
Thanks for your pull request.

But I'm afraid I can't integrate this code as-is, at it is not generic and clean enough:
- You should not store your cached file in the same directory as the input path. For example, if the path is obtained (which would typically be the case) by `[[NSBundle mainBundle] pathForResource:ofType:]`, your code won't work as it is forbidden to write files in the bundle (and it would invalidate your binary's code signature)
- You may instead use the "Cache" directory (`NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES);` etc) of your app's sandbox to store your cached file.
- If you do that, you should provide a mechanism to empty this cached resized images, to avoid your sandbox to grow in size too much, because the longer your users will use your app and download more images that will be resized and stored in your cache, the more size it will occupy on the user's device.
- You may also instead use the `NSTemporaryDirectory()` that will be cleaned by iOS when your app stops running, avoiding your sandbox to grow between launches of your application and making it clean itself.

But of course if you manage to fix those issues, I'll be happy to merge your new version in the master branch :)

**Comment by j-mcnally** [comment]
Great thoughts!!! I will revise my implementation since I am using it in a
project thanks for the tips.

**Comment by AliSoftware** [comment]
Some other suggestions:
- Use GCD to deport the writing of your cache file on a dedicated queue, to avoid blocking the current thread (which will generally be the main thread). This will improve performance and execution time, as writing to the disk may take some time. Especially imagine a case when you use resized images in an `UITableView`, writing your cache file on the current (generally main) thread will make the scrolling of your UITableView to be quite slow. So I think this consideration is quite important
- But to do that correctly and avoid bugs, don't forget the case when you would ask for the same image with the same size twice in a close time range (again quite typical when scrolling quite fast in an `UITableView`): if the second time you ask for this image, the code of the first call that writes the cached resized image didn't have time to finish yet, your second call won't find the cached file as it won't exist yet.

_You can for example use some `NSDictionary` indexed by the `cacheFilePath` of you files being written, and some semaphore or lock objects (or any other synchronization mechanism) to block any other calls for the exact same file and size while its corresponding cache file is still being written in the background. Or any other solution that you find suitable, like changing your method signature to avoid returning the UIImage directly but return in asynchronously using a `completionBlock`, or whatever solution that will avoid blocking the main thread in those cases._

**Comment by AliSoftware** [comment]
Note: I'm closing this pull request as you'll probably open a new one when your updated code (that works with images in bundle) will be ready

**Pull request closed without merging**
